linters:
  # Disable all linters.
  # Default: false
  disable-all: true
  # Enable specific linter
  # https://golangci-lint.run/usage/linters/#enabled-by-default
  enable:
    - errcheck
    - gocritic
    - gocyclo
    - golint
    - gosimple
    - interfacer
    - lll
    - misspell
    - staticcheck
    - structcheck
    - stylecheck
